spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bingo
    username: nekro_agent
    password: nekro_agent
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  forward-headers-strategy: native